Detect global config from env etc
equinor/fmu-dataio pull request #129
Opened 2021-11-11 09:28 UTC by jcrivenaes

Either, in case the `config` key is not present or set None:

- Set env variable `FMU_DATAIO_CONFIG` to point to the YAML file that shall be input to the `config` key
- Look for `../../fmuconfig/output/global_variables.yml`

This will simplify for e.g. script running in an ERT forward model

2021-11-12 14:22 UTC, perolavsvendsen requested changes
See comment on relative reference. May not be relevant, but unclear to me.

2021-11-15 17:20 UTC, jcrivenaes commented on src/fmu/dataio/dataio.py
> +        envvar = "FMU_DATAIO_CONFIG"
The alternative is to name it `FMU_GLOBAL_CONFIG`, but I was thinking on corner cases where one wanted to separate the FMU global config and some other config specific for dataio. However I can roll back to `FMU_GLOBAL_CONFIG` and solve the corner cases when they occur (i.e. having multiple env variables with a priority)

2021-11-15 17:21 UTC, jcrivenaes commented on src/fmu/dataio/dataio.py
> +        cfg_file = pathlib.Path("../../fmuconfig/output/global_variables.yml")
I will remove this as we discussed. A bit too dangerous to have fixed paths; instead rather focus on using the env variable

2021-11-15 17:24 UTC, perolavsvendsen commented on src/fmu/dataio/dataio.py
> +        envvar = "FMU_DATAIO_CONFIG"
OK I'm fine with the as-is, just wondered about the logic 👍

2021-11-15 17:36 UTC, perolavsvendsen commented on src/fmu/dataio/dataio.py
> +            logger.info("Try global config from env variable %s as %s", envvar, cfg)
Change from "try" to "found"?

2021-11-15 17:43 UTC, perolavsvendsen approved these changes
LGTM

2021-11-15 20:05 UTC, jcrivenaes commented on src/fmu/dataio/dataio.py
> +            logger.info("Try global config from env variable %s as %s", envvar, cfg)
Good catch; I changed to "Set"

2021-11-16 09:49 UTC, merged