Include dict
equinor/fmu-dataio pull request #355
Opened 2023-07-07 08:13 UTC by daniel-sol

Suggested solution to issue #354

2023-07-07 08:41 UTC, perolavsvendsen commented on src/fmu/dataio/_definitions.py
> +        self.dictionary = {"json": ".json", "yaml": ".yml"}
Good example of something that will be potentially very difficult to understand 6 months from now, without the context. If we move on with the `dictionary` as a class, we probably need to explain this with comments. If we have no better options, we will have to go with it, but this is a major code smell I think.

2023-07-07 08:45 UTC, perolavsvendsen requested changes
Need tests that clearly show how we intend this to be used. At least some unit tests. Suggestions:
- Have dict instance, export it with metadata. Assert results are as expected.
- Open JSON file from disk, create metadata
- Open non-JSON file from disk, turn it into JSON, create metadata
- Try to pass a dictionary that cannot be turned into JSON - how does the code handle that, and what error messages are given?

Specific use case is `parameters.txt` I believe. Perhaps add that explicitly as a test, which will be something between unit testing and integration testing I guess.

2023-07-11 08:35 UTC, equinor-ruaj commented on src/fmu/dataio/_objectdata_provider.py
> +        logger.info("Process data metadata for arrow (tables)")
Is this docstring and logging correct?

2023-07-11 10:40 UTC, daniel-sol commented on src/fmu/dataio/_objectdata_provider.py
> +        logger.info("Process data metadata for arrow (tables)")
Nope, well spotted. Changed now..

2023-07-11 10:41 UTC, equinor-ruaj approved these changes
lgtm

2023-07-11 19:41 UTC, perolavsvendsen approved these changes
OK let's try it and see how it works. Gut feeling that this might be confusing, but I don't see any better options. This PR should probably include a documentation update, but I guess there are more that should be included there... 

This PR should trigger a new version of fmu-dataio.

2023-07-12 07:24 UTC, merged