ENH: Add platform field to event-tracklog
equinor/fmu-dataio pull request #440
Opened 2024-01-30 18:24 UTC by janbjorge

2024-02-01 13:32 UTC, janbjorge commented on src/fmu/dataio/datastructure/meta/meta.py
> +import platform as _platform
Must be given a _ prefix due to name collision in FMUdataioSystemInformationPlatform

2024-02-01 13:37 UTC, janbjorge commented on src/fmu/dataio/datastructure/meta/meta.py
> +    version: str = Field(default_factory=_platform.version)
This approach might get tricky as we scale due to circular dependencies.

2024-02-12 12:01 UTC, jcrivenaes commented on src/fmu/dataio/datastructure/meta/meta.py
>  from typing import Dict, List, Literal, Optional, Union
Why just not:
`import platform
`
and then later:

`platform.platform` (instead of `platform_platform`) etc

2024-02-12 13:00 UTC, perolavsvendsen commented
Are there security concerns to take into account? These data are to be shared with externals, we must assume that they will be made available to anyone. Are we OK exposing exactly which platforms we are running FMU on internally?

2024-02-12 13:39 UTC, janbjorge commented
> Is `platform` the best word? (`operating_system`?) (Platform means many things, and especially in the oil industry, the word "platform" has a few additional meanings.)
> 
> How do we know that this works on all platforms? Tested so far on Mac, I assume. Those that comes to mind:
> 
>     * [ ]  Unix (RGS)
> 
>     * [ ]  Unix (LSF)
> 
>     * [ ]  Unix (Radix, Azure, etc)
> 
>     * [ ]  Windows

Its a builtin python package, i would be amazed if the does not work on all python supported platforms. However, how can i test for other platforms / operating systems?

2024-02-12 13:44 UTC, janbjorge commented
> Are there security concerns to take into account? These data are to be shared with externals, we must assume that they will be made available to anyone. Are we OK exposing exactly which platforms we are running FMU on internally?

Good question, if there is a known security weakness in a version we using this could potentially be used as a discriminator.

2024-02-12 13:50 UTC, jcrivenaes commented
> > Is `platform` the best word? (`operating_system`?) (Platform means many things, and especially in the oil industry, the word "platform" has a few additional meanings.)
> > How do we know that this works on all platforms? Tested so far on Mac, I assume. Those that comes to mind:
> > ```
> > * [ ]  Unix (RGS)
> > 
> > * [ ]  Unix (LSF)
> > 
> > * [ ]  Unix (Radix, Azure, etc)
> > 
> > * [ ]  Windows
> > ```
> 
> Its a builtin python package, i would be amazed if the does not work on all python supported platforms. However, how can i test for other platforms / operating systems?

Yes agree it should work in general. For me, this is "nice to have" information; not something "critical" we need to make dataio/sumo work.

2024-02-12 13:51 UTC, jcrivenaes approved these changes
OK for me

2024-02-12 13:56 UTC, janbjorge commented
Change since last review.
- renamed platform -> operating_system
- Added test
- Moved object initialization to _metadata.py

2024-02-12 13:59 UTC, janbjorge commented
> > > Is `platform` the best word? (`operating_system`?) (Platform means many things, and especially in the oil industry, the word "platform" has a few additional meanings.)
> > > How do we know that this works on all platforms? Tested so far on Mac, I assume. Those that comes to mind:
> > > ```
> > > * [ ]  Unix (RGS)
> > > 
> > > * [ ]  Unix (LSF)
> > > 
> > > * [ ]  Unix (Radix, Azure, etc)
> > > 
> > > * [ ]  Windows
> > > ```
> > 
> > 
> > Its a builtin python package, i would be amazed if the does not work on all python supported platforms. However, how can i test for other platforms / operating systems?
> 
> Yes agree it should work in general. For me, this is "nice to have" information; not something "critical" we need to make dataio/sumo work.

I checked out the source for plaform quick, and i see code for windows in there. So for now, i think its safe to assume so.

https://github.com/python/cpython/blob/3.12/Lib/platform.py

2024-02-12 14:03 UTC, perolavsvendsen requested changes
I think this is fine, but we should confirm the security implications before we merge.

2024-02-13 08:24 UTC, perolavsvendsen approved these changes
Based on inputs from community, I consider the potential risk very low. Still a question about how much is _needed_ to include here, but that can also be adjusted over time.

2024-02-13 08:24 UTC, merged